// <auto-generated />
namespace _1GemmyModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init5142 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init5142));
        
        string IMigrationMetadata.Id
        {
            get { return "202105140117271_init5142"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
