// <auto-generated />
namespace _1GemmyModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init33332 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init33332));
        
        string IMigrationMetadata.Id
        {
            get { return "202104290120236_init33332"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
