// <auto-generated />
namespace _1GemmyModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initorder123456222 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initorder123456222));
        
        string IMigrationMetadata.Id
        {
            get { return "202109130126429_initorder123456222"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
