// <auto-generated />
namespace _1GemmyModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init1234565432 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init1234565432));
        
        string IMigrationMetadata.Id
        {
            get { return "202105130310094_init1234565432"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
